GET http://localhost:3001/characters
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoibHVjaWFubyIsImVtYWlsIjoibHVjaWFub0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQvQURocldsdTdIQ3MuQ3g1SXJVdWplQS9qZURYbWQxMmVwNlEwSHVTYzdkTlhQTVJNTjdTZSJ9LCJpYXQiOjE2NDYwOTI4ODUsImV4cCI6MTY0NjY5NzY4NX0.dR_gi5GnOJEpgyw7kHgCUTJNAGWMgoJXPsZKTfGZvsU